### ISSUE TITLE
fix(net): Payload Conversion Utilities

### ISSUE THREAD

**Issue by refcell** [ithacaxyz/op-rs#79]
### Description

https://github.com/paradigmxyz/op-rs/pull/74 updates the networking crate to use upstream alloy execution payload types, converting those types into kona's `L2ExecutionPayload`.

These conversions are upstreamed in [a pr](https://github.com/anton-rs/kona/pull/470) currently. It's failing though since `alloy-rpc-types-engine` uses the standard library. This issue is to attempt to convert the [alloy-rpc-types-engine](https://github.com/alloy-rs/alloy/tree/main/crates/rpc-types-engine) crate to the `no_std` environment.

### Additional Context

https://github.com/paradigmxyz/op-rs/pull/74#discussion_r1740102121

**Comment by GrapeBaBa** [comment]
@refcell Does it mean changes in [alloy-rpc-types-engine](https://github.com/alloy-rs/alloy/tree/main/crates/rpc-types-engine) repo and remove the reference `std`?

**Comment by GrapeBaBa** [comment]
@refcell Is my understanding correct? Or can you explain more?
